# Generated by Django 3.2.5 on 2021-07-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lanzamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='lanzamientos')),
                ('nombre', models.CharField(max_length=50)),
                ('plataforma', models.CharField(choices=[('Nintendo Switch', 'Nintendo Switch'), ('Xbox', 'Xbox'), ('Playstation', 'Playstation'), ('PC', 'PC'), ('Multiplataforma', 'Multiplataforma'), ('No informada', 'No informada')], max_length=50)),
                ('descripcion', models.CharField(max_length=1000)),
            ],
        ),
    ]
