# Generated by Django 3.2.5 on 2021-07-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lanzamientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanzamiento',
            name='descripcion',
            field=models.TextField(max_length=1000),
        ),
    ]
