# Generated by Django 3.2.5 on 2021-07-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lanzamientos', '0003_lanzamiento_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanzamiento',
            name='foto',
            field=models.ImageField(upload_to='static/img/lanzamientos'),
        ),
    ]
